### ISSUE TITLE
Unable to download datasets by aws s3 links 

### ISSUE THREAD

**Issue by rakhnin** [klarna/product-page-dataset#22]
Got an 403 error.

**Comment by stefanmagureanu** [comment]
Hi Rakhnin, according to my understanding the dataset will be available again soon while a few things are being ironed out with how it is being hosted. I don't know a timeline since it's up to the peeps at Klarna, but it should be back online well before the NeurIPS Dataset and Benchmarks track. We just need to be patient a bit, hope this info helps.

**Comment by rakhnin** [comment]
@stefanmagureanu Thanks for the info, will be waiting.
